"""Public product interface for the Strategy Diagnostics Laboratory."""

from .application import (
    DIAGNOSTIC_SCHEMA_REVISION,
    DiagnosticsApplication,
    DiagnosticsApplicationState,
    create_diagnostics_application,
)
from .baostock_source import BaoStockHistoricalSource, BaoStockSourceLayout
from .historical_segments import (
    AdmissionCheck,
    HistoricalMarketSegment,
    HistoricalSegmentRecommendation,
    HistoricalSegmentSelection,
    HistoricalSourceInspection,
    InMemoryHistoricalSource,
    SegmentAdmissionReport,
    SourceArtifact,
    SourceProvenance,
    SourceSnapshot,
)
from .market_paths import (
    EligibleUniverseAccessError,
    FiveMinuteBar,
    FutureDataAccessError,
    HistoricalMarketDataSource,
    InMemoryHistoricalMarketDataSource,
    InMemoryMarketPathArtifactStore,
    InstrumentState,
    MarketPathArtifactStore,
    MarketPathNode,
    MaterializedMarketPath,
    ParquetMarketPathArtifactStore,
    ScenarioDataWorldInput,
    ScenarioMarketSnapshot,
    ScenarioMarketView,
    ScenarioMaterializer,
)

__all__ = [
    "DIAGNOSTIC_SCHEMA_REVISION",
    "DiagnosticsApplication",
    "DiagnosticsApplicationState",
    "BaoStockHistoricalSource",
    "BaoStockSourceLayout",
    "AdmissionCheck",
    "HistoricalMarketSegment",
    "HistoricalSegmentRecommendation",
    "HistoricalSegmentSelection",
    "HistoricalSourceInspection",
    "InMemoryHistoricalSource",
    "SegmentAdmissionReport",
    "SourceArtifact",
    "SourceProvenance",
    "SourceSnapshot",
    "EligibleUniverseAccessError",
    "FiveMinuteBar",
    "FutureDataAccessError",
    "HistoricalMarketDataSource",
    "InMemoryHistoricalMarketDataSource",
    "InMemoryMarketPathArtifactStore",
    "InstrumentState",
    "MarketPathArtifactStore",
    "MarketPathNode",
    "MaterializedMarketPath",
    "ParquetMarketPathArtifactStore",
    "ScenarioDataWorldInput",
    "ScenarioMarketSnapshot",
    "ScenarioMarketView",
    "ScenarioMaterializer",
    "create_diagnostics_application",
]
