from __future__ import annotations

from threading import RLock
from typing import Any, Dict, Iterable, Optional

from app.controllers.market_controller import MarketController
from app.utils.validators import safe_float, safe_int

try:
    from observability.metrics import metrics  # type: ignore
except Exception:  # pragma: no cover
    class _Dummy:
        def inc(self, *_, **__):
            pass

    metrics = _Dummy()

__all__ = ["CreateInstrumentDialog", "register_create_instrument_dialog", "suggest_next_symbol"]


def suggest_next_symbol(existing_symbols: Iterable[str] | None = None) -> str:
    highest = 0
    for raw in existing_symbols or []:
        text = str(raw or "").strip()
        if len(text) == 3 and text.isdigit():
            highest = max(highest, int(text))
    return f"{highest + 1:03d}"


class CreateInstrumentDialog:
    """Pure logic for create-instrument form state.

    Product-level constraints for the current desktop flow:
    - `symbol` is generated by the UI and read-only.
    - users edit `name`, `initial_price`, and `float_shares`.
    - `market_cap` is derived and shown as a preview only.
    """

    def __init__(self, controller: MarketController, *, price_step: float = 0.01):
        self._ctl = controller
        self._lock = RLock()
        self._name: str = ""
        self._symbol: str = ""
        self._initial_price: Optional[str] = None
        self._float_shares: Optional[str] = None
        self._market_cap: Optional[str] = None
        self._total_shares: Optional[str] = None
        self._norm_price: Optional[float] = None
        self._norm_float_shares: Optional[int] = None
        self._norm_market_cap: Optional[float] = None
        self._norm_total_shares: Optional[int] = None
        self._price_step = price_step
        self._errors: Dict[str, str] = {}
        self._last_error: Optional[str] = None
        self._last_result: Optional[Dict[str, Any]] = None

    def set_fields(
        self,
        *,
        name: Optional[str] = None,
        symbol: Optional[str] = None,
        initial_price: Optional[str] = None,
        float_shares: Optional[str] = None,
        market_cap: Optional[str] = None,
        total_shares: Optional[str] = None,
    ) -> None:
        with self._lock:
            if name is not None:
                self._name = name
            if symbol is not None:
                self._symbol = symbol
            if initial_price is not None:
                self._initial_price = initial_price if initial_price != "" else None
            if float_shares is not None:
                self._float_shares = float_shares if float_shares != "" else None
            if market_cap is not None:
                self._market_cap = market_cap if market_cap != "" else None
            if total_shares is not None:
                self._total_shares = total_shares if total_shares != "" else None
            self._recompute()

    def clear(self) -> None:
        with self._lock:
            self.__init__(self._ctl, price_step=self._price_step)

    def _recompute(self) -> None:
        self._errors.clear()
        self._last_error = None
        self._last_result = None

        name = (self._name or "").strip()
        symbol = (self._symbol or "").strip().upper()
        if not name:
            self._errors["name"] = "ERR_EMPTY_NAME"
        if not symbol:
            self._errors["symbol"] = "ERR_EMPTY_SYMBOL"

        norm_price = None
        norm_float_shares = None
        norm_market_cap = None
        norm_total_shares = None

        if self._initial_price is None:
            self._errors["initial_price"] = "ERR_EMPTY_INITIAL_PRICE"
        else:
            try:
                norm_price = safe_float(self._initial_price, min_value=0)
                if norm_price <= 0:
                    raise ValueError("non-positive")
            except Exception:
                self._errors["initial_price"] = "ERR_PRICE_INVALID"

        if self._float_shares is None:
            self._errors["float_shares"] = "ERR_EMPTY_FLOAT_SHARES"
        else:
            try:
                norm_float_shares = safe_int(self._float_shares, min_value=0)
                if norm_float_shares <= 0:
                    raise ValueError("non-positive")
            except Exception:
                self._errors["float_shares"] = "ERR_FLOAT_SHARES_INVALID"

        if self._market_cap is not None:
            try:
                norm_market_cap = safe_float(self._market_cap, min_value=0)
                if norm_market_cap <= 0:
                    raise ValueError("non-positive")
            except Exception:
                self._errors["market_cap"] = "ERR_MARKET_CAP_INVALID"

        if self._total_shares is not None:
            try:
                norm_total_shares = safe_int(self._total_shares, min_value=0)
            except Exception:
                self._errors["total_shares"] = "ERR_TOTAL_SHARES_INVALID"

        missing_triad = sum(
            value is None
            for value in (self._initial_price, self._float_shares, self._market_cap)
        )
        if missing_triad != 1:
            self._errors["triad"] = "ERR_TRIAD_NEED_EXACTLY_ONE_EMPTY"

        if norm_market_cap is None and norm_price is not None and norm_float_shares is not None:
            norm_market_cap = float(norm_price) * int(norm_float_shares)
        elif norm_price is None and norm_market_cap is not None and norm_float_shares:
            norm_price = float(norm_market_cap) / int(norm_float_shares)
        elif norm_float_shares is None and norm_market_cap is not None and norm_price:
            try:
                norm_float_shares = int(round(float(norm_market_cap) / float(norm_price)))
            except Exception:
                norm_float_shares = None

        if norm_total_shares is not None and norm_float_shares is not None and norm_total_shares < norm_float_shares:
            self._errors["total_shares"] = "ERR_TOTAL_LT_FLOAT"

        self._name = name
        self._symbol = symbol
        self._norm_price = norm_price
        self._norm_float_shares = norm_float_shares
        self._norm_market_cap = norm_market_cap
        self._norm_total_shares = norm_total_shares

    def get_view(self) -> Dict[str, Any]:
        with self._lock:
            return {
                "fields": {
                    "name": self._name,
                    "symbol": self._symbol,
                    "initial_price": self._initial_price,
                    "float_shares": self._float_shares,
                    "market_cap": self._market_cap if self._market_cap is not None else self._norm_market_cap,
                    "total_shares": self._total_shares,
                },
                "normalized": {
                    "initial_price": self._norm_price,
                    "float_shares": self._norm_float_shares,
                    "market_cap": self._norm_market_cap,
                    "total_shares": self._norm_total_shares,
                },
                "derived": {
                    "field": "market_cap" if self._norm_market_cap is not None else None,
                    "value": self._norm_market_cap,
                    "original_missing": "market_cap",
                },
                "errors": dict(self._errors),
                "is_valid": len(self._errors) == 0,
                "last_result": self._last_result,
                "last_error": self._last_error,
            }

    def submit(self) -> bool:
        with self._lock:
            self._recompute()
            if self._errors:
                self._last_error = "ERR_FORM_INVALID"
                return False
            name = self._name
            symbol = self._symbol
            price = self._norm_price
            float_shares = self._norm_float_shares
            market_cap = self._norm_market_cap if self._market_cap is not None else None
            total_shares = self._norm_total_shares if self._norm_total_shares is not None else float_shares
        try:
            payload = self._ctl.create_instrument(
                name=name,
                symbol=symbol,
                initial_price=price,
                float_shares=float_shares,
                market_cap=market_cap,
                total_shares=total_shares,
                price_step=self._price_step,
            )
            with self._lock:
                self._last_result = payload
                self._last_error = None
            metrics.inc("create_instrument_dialog_submit")
            return True
        except Exception:  # noqa: BLE001
            with self._lock:
                self._last_error = "ERR_SUBMIT_FAILED"
            metrics.inc("create_instrument_dialog_error")
            return False


from app.panels import replace_panel  # noqa: E402


def register_create_instrument_dialog(controller: MarketController):
    replace_panel(
        "create_instrument",
        lambda: CreateInstrumentDialog(controller),
        title="CreateInstrument",
        meta={"i18n_key": "dialog.create_instrument"},
    )
